location /api/ {
  proxy_pass https://mytonstorage.org/api/;
  proxy_set_header Host mytonstorage.org;
  proxy_http_version 1.1;

  proxy_ssl_server_name on;
  proxy_ssl_verify on;
  proxy_ssl_verify_depth 4;
  proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;

  client_max_body_size 4g;
  proxy_read_timeout 600s;
  proxy_send_timeout 600s;
  proxy_request_buffering off;
  proxy_buffering off;
}
